/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2017-07-25 16:13:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.layouts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class default_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/D:/dev_tools/apache-tomcat-8.0.23/webapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/layouts/menu.jsp", Long.valueOf(1500995180015L));
    _jspx_dependants.put("/WEB-INF/layouts/header.jsp", Long.valueOf(1500995179484L));
    _jspx_dependants.put("/WEB-INF/layouts/footer.jsp", Long.valueOf(1500995180818L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500995551149L));
    _jspx_dependants.put("jar:file:/D:/dev_tools/apache-tomcat-8.0.23/webapps/ssm/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123649492000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1500995555085L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<title>『游鱼圈』推广系统管理后台</title>\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-1.10.2.min.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validateForm.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.dialog.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ueditor/ueditor.config.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ueditor/ueditor.all.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/MD5.js\"></script>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/default.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/jquery.dialog.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ueditor/themes/default/css/ueditor.css\"/>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\tfunction gotopage(url, pageno)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\twindow.location.href = url + '?pageno=' + pageno;\n");
      out.write("\t\t\t}\n");
      out.write("\t   </script>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t   <div class=\"page\">\n");
      out.write("\t\t\t");
if(request.getRequestURI().indexOf("/user/login") > -1 || request.getRequestURI().indexOf("/wechatpay/topay") > -1 || request.getRequestURI().indexOf("/wechatpay/payurl") > -1 || request.getRequestURI().indexOf("/wechatpay/notify") > -1 || request.getRequestURI().indexOf("/wechatpay/re_notify") > -1){
      out.write("\n");
      out.write("\t\t\t\t<div>");
      if (_jspx_meth_sitemesh_005fbody_005f0(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("\t\t\t");
}else{
      out.write("\n");
      out.write("\t\t\t<div class=\"center\">\n");
      out.write("\t\t\t    <div class=\"header\" name=\"headerdivdivdiv\" id=\"headerdivdivdiv\">");
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<div>\n");
      out.write("    <div style=\"width:75%;;float:left;\">\n");
      out.write("         <div style=\"height: 70px; font-size: 18px;font-weight: bold; line-height: 65px;\">\n");
      out.write("         \t<div style=\"width: 15%;background: #34485b;\">\n");
      out.write("\t\t   \t\t<img src=\"../images/logobg.png\" style=\"height: 44px; margin-left: 44px; margin-top: 12px; float: left;\" />\n");
      out.write("\t\t   \t</div>\n");
      out.write("\t\t    <div style=\"font-size:20px;font-weight:bold;color:#e6e6e6;width:60%;height: 70px;float: left;margin-left:20px;line-height: 71px;\">『游鱼圈』推广系统管理后台</div>\n");
      out.write("\t\t</div>\n");
      out.write("    </div>\n");
      out.write("\t<div style=\"font-weight: bold;float:left;width: 16%;height:70px;line-height:70px;font-size: 18px;color: #e6e6e6;\">欢迎您，");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("! &nbsp;<label style=\"color: #f59700;\">");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("</label></div>\n");
      out.write("\t<div style=\"float: left;width:9%; margin-top:11px;\">\n");
      out.write("\n");
      out.write("\t\t<div style=\"width: 80px; font-size: 18px; font-weight: bold; color: #ff6600; cursor: pointer; margin-top: 7px;\" onclick=\"if(window.confirm('确定要退出？')) window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/logout';\">『退出』</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"clear\"></div>\n");
      out.write("</div>\n");
      out.write("<div class=\"spacer\"></div>\n");
      out.write("</div>\n");
      out.write("\t\t\t \t<div class=\"floatleft menu\" id=\"menudivdiv\" name=\"menudivdiv\">\n");
      out.write("\t\t\t\t \t<!-- <iframe id=\"commoditylist\" name=\"commoditylist\" src=\"/WEB-INF/layouts/menu.jsp\" style=\"width: 100%;height:100%\" scrolling=\"no\" frameborder =\"0\"  >\n");
      out.write("\t\t\t\t\t</iframe> -->\n");
      out.write("\t\t\t     \t");
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\n');
   
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
com.songfayuan.ssm.controller.CheckUserRight checkUserRight = new  com.songfayuan.ssm.controller.CheckUserRight(request);

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(100)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click1\" id=\"click1\" onclick=\"changeColor(this,1)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle1\" onclick=\"goIndex()\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/shouye.png\" class=\"icon\">首页</div>\n");
      out.write("\t");
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(200)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click2\" id=\"click2\" onclick=\"changeColor(this,2)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle2\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/kehu.png\" class=\"icon\">接单人管理</div>\n");
      out.write("\t");
if(checkUserRight.check(200001)){ 
      out.write("\n");
      out.write("\t\t<div class=\"menuitem\" name=\"menuitem2\" onclick=\"getColor(2)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a  id=\"abq2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/userlist\">接单人列表</a></div>\n");
      out.write("\t");
}
      out.write('\n');
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(300)){ 
      out.write(" \n");
      out.write("<div class=\"menupanel\" name=\"click3\" id=\"click3\" onclick=\"changeColor(this,3)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle3\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/wenjuan.png\" class=\"icon\">订单管理</div>\n");
      out.write("\t");
if(checkUserRight.check(300001)){ 
      out.write("\n");
      out.write("\t\t<div class=\"menuitem\" name=\"menuitem3\" onclick=\"getColor(5)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq5\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/content/add\">发布订单</a></div>\n");
      out.write("\t");
}
      out.write('\n');
      out.write('	');
if(checkUserRight.check(300002)){ 
      out.write("\n");
      out.write("\t\t<div class=\"menuitem\" name=\"menuitem3\" onclick=\"getColor(4)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq4\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/content/list\">订单列表</a></div>\n");
      out.write("\t");
}
      out.write('\n');
      out.write('	');
if(checkUserRight.check(300003)){ 
      out.write("\n");
      out.write("\t\t<div class=\"menuitem\" name=\"menuitem3\" onclick=\"getColor(6)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq6\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/content/admin_list\">订单审核</a></div>\n");
      out.write("\t");
}
      out.write('\n');
      out.write('	');
if(checkUserRight.check(300004)){ 
      out.write("\n");
      out.write("\t\t<div class=\"menuitem\" name=\"menuitem3\" onclick=\"getColor(7)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq7\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/content/detail_list\">订单详情</a></div>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(400)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click4\" id=\"click4\" onclick=\"changeColor(this,4)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle4\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/chongzhi.png\" class=\"icon\">充值管理</div>\n");
      out.write("\t");
if(checkUserRight.check(400001)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem4\" onclick=\"getColor(8)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq8\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payrecord/list\">充值记录</a></div>\n");
      out.write("    ");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write(' ');
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(500)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click5\" id=\"click5\" onclick=\"changeColor(this,5)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle5\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/baobiao.png\" class=\"icon\">财务报表</div>\n");
      out.write("\t");
if(checkUserRight.check(500001)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem5\" onclick=\"getColor(11)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq11\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payrecord/financial_statement\">报表详情</a></div>\n");
      out.write("\t");
}
      out.write('\n');
      out.write('	');
if(checkUserRight.check(500002)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem5\" onclick=\"getColor(19)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq19\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payrecord/personal_financial_statement\">个人报表详情</a></div>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write(' ');
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(600)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click6\" id=\"click6\" onclick=\"changeColor(this,6)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle6\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/quanxian.png\" class=\"icon\">权限管理</div>\n");
      out.write("\t");
if(checkUserRight.check(600001)){ 
      out.write("\n");
      out.write("\t\t<div class=\"menuitem\" name=\"menuitem6\" onclick=\"getColor(12)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq12\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/rolelist\">权限管理</a></div>\n");
      out.write("\t");
}if(checkUserRight.check(600002)){ 
      out.write("\n");
      out.write("\t\t<div class=\"menuitem\" name=\"menuitem6\" onclick=\"getColor(13)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq13\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/adminlist\">管理员管理</a></div>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(700)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click7\" id=\"click7\" onclick=\"changeColor(this,7)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle7\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/yunxingrizhi.png\" class=\"icon\">运行日志</div>\n");
      out.write("\t");
if(checkUserRight.check(700001)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem7\" onclick=\"getColor(14)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq14\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/log/list\">日志列表</a></div>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(800)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click8\" id=\"click8\" onclick=\"changeColor(this,8)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle8\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/kehu.png\" class=\"icon\">人群标志管理</div>\n");
      out.write("\t");
if(checkUserRight.check(800001)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem8\" onclick=\"getColor(15)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq15\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/population/list\">人群标志列表</a></div>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(900)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click9\" id=\"click9\" onclick=\"changeColor(this,9)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle9\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/tixian.png\" class=\"icon\">提现管理</div>\n");
      out.write("\t");
if(checkUserRight.check(900001)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem9\" onclick=\"getColor(16)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq16\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/record/apply_list\">申请中</a></div>\n");
      out.write("\t");
}
      out.write('\n');
      out.write('	');
if(checkUserRight.check(900002)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem9\" onclick=\"getColor(17)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq17\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/record/handle_list\">处理中</a></div>\n");
      out.write("\t");
}
      out.write('\n');
      out.write('	');
if(checkUserRight.check(900003)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem9\" onclick=\"getColor(18)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq18\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/record/end_list\">已完成</a></div>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
if(checkUserRight.check(1000)){ 
      out.write("\n");
      out.write("<div class=\"menupanel\" name=\"click10\" id=\"click10\" onclick=\"changeColor(this,10)\">\n");
      out.write("\t<div class=\"menutitle\" id=\"menutitle10\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/fuzhu.png\" class=\"_img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/canshushezhi.png\" class=\"icon\">密码更改</div>\n");
      out.write("\t");
if(checkUserRight.check(1000001)){ 
      out.write("\n");
      out.write("\t<div class=\"menuitem\" name=\"menuitem10\" onclick=\"getColor(19)\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/icon/subimg.png\" class=\"_subimg\"><a id=\"abq19\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/toeidtadminpw\">修改登录密码</a></div>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("    var UA = navigator.userAgent.toLowerCase().toString(); \n");
      out.write("    \n");
      out.write("    var usertype = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.usertype }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";//用户类型\n");
      out.write("    \n");
      out.write("    function goIndex()\n");
      out.write("    {\n");
      out.write("    \tif(usertype==202){\n");
      out.write("    \t\twindow.location.href=\"");
      out.print(basePath);
      out.write("user/userindex\";\n");
      out.write("    \t}else{\n");
      out.write("\t    \twindow.location.href=\"");
      out.print(basePath);
      out.write("user/index?flag=sy\";\n");
      out.write("    \t}\n");
      out.write("    }\n");
      out.write("    // 兼容IE FF的ByName方法  \n");
      out.write("    var getElementsByName = function(tag, name){  \n");
      out.write("    \t\n");
      out.write("        var returns = document.getElementsByName(name);  \n");
      out.write("        if(returns.length > 0) return returns;  \n");
      out.write("        returns = new Array();  \n");
      out.write("        var e = document.getElementsByTagName(tag);  \n");
      out.write("        for(var i = 0; i < e.length; i++){  \n");
      out.write("            if(e[i].getAttribute(\"name\") == name){  \n");
      out.write("                returns[returns.length] = e[i];  \n");
      out.write("            }  \n");
      out.write("        }  \n");
      out.write("        return returns;  \n");
      out.write("    };\n");
      out.write("    \n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t\n");
      out.write("\t\tvar id=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\tvar iscolor=window.sessionStorage.getItem(\"isColor\");\n");
      out.write("\t\t\n");
      out.write("\t \t$(\"div.menuitem\").each(function(index){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(this).css(\"display\",\"none\");\n");
      out.write("\t\t}); \n");
      out.write("\t\t\n");
      out.write("\t\tif(/(msie\\s|trident.*rv:)([\\w.]+)/.test(UA)){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(id!=\"\"&&id!=null&&id!='undefined'){\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar objs=getElementsByName(\"div\",\"menuitem\"+id);\n");
      out.write("\t\t\t\tdocument.getElementById(\"menutitle\"+id).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\tfor ( var i = 0; i < objs.length; i++) {\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tobjs[i].style.display=\"block\";  \n");
      out.write("\t\t\t\t\tdocument.getElementById(\"abq\"+iscolor).style.color=\"#31a3ff\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(id!=\"\"&&id!=null&&id!='undefined'){\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar objs=document.getElementsByName(\"menuitem\"+id);\n");
      out.write("\t\t\t\tdocument.getElementById(\"menutitle\"+id).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\tfor ( var i = 0; i < objs.length; i++) {\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tobjs[i].style.display=\"block\";  \n");
      out.write("\t\t\t\t\tdocument.getElementById(\"abq\"+iscolor).style.color=\"#31a3ff\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tfunction changeColor(obj,id){\n");
      out.write("\t\t\n");
      out.write("\t//\talert(\"changeColor\"+id);\n");
      out.write("\t\twindow.sessionStorage.setItem(\"isClick\",id);\n");
      out.write("\t\n");
      out.write("\t} \n");
      out.write("\t\n");
      out.write("\tfunction getColor(id){\n");
      out.write("\t\t\n");
      out.write("\t//\talert(\"getColor\"+id);\n");
      out.write("\t\twindow.sessionStorage.setItem(\"isColor\",id);\n");
      out.write("\t} \n");
      out.write("\t\n");
      out.write("\t//针对360极速游览器和360安全游览器 \n");
      out.write("\tif(/(msie\\s|trident.*rv:)([\\w.]+)/.test(UA)){\t\n");
      out.write("\t\t\n");
      out.write("\t\tvar click1=document.getElementById(\"click1\");\n");
      out.write("\t\tclick1.onclick = function(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\twindow.sessionStorage.setItem(\"isClick\",1);\n");
      out.write("\t\t\tif($(this).children('div.menuitem').length > 0 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#34485b\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    };\n");
      out.write("\t    var click2=document.getElementById(\"click2\");\n");
      out.write("\t    click2.onclick = function(){\n");
      out.write("\t\t\t\n");
      out.write("\t    \twindow.sessionStorage.setItem(\"isClick\",2);\n");
      out.write("\t\t\tif($(this).children('div.menuitem').length > 0 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    }; \n");
      out.write("\t    \n");
      out.write("\t    var click3=document.getElementById(\"click3\");\n");
      out.write("\t    click3.onclick = function(){\n");
      out.write("\t\t\t\n");
      out.write("\t    \twindow.sessionStorage.setItem(\"isClick\",3);\n");
      out.write("\t\t\tif($(this).children('div.menuitem').length > 0 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    }; \n");
      out.write("\t    \n");
      out.write("\t    var click4=document.getElementById(\"click4\");\n");
      out.write("\t    click4.onclick = function(){\n");
      out.write("\t\t\t\n");
      out.write("\t    \twindow.sessionStorage.setItem(\"isClick\",4);\n");
      out.write("\t\t\tif($(this).children('div.menuitem').length > 0 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    }; \n");
      out.write("\t    \n");
      out.write("\t    var click5=document.getElementById(\"click5\");\n");
      out.write("\t    click5.onclick = function(){\n");
      out.write("\t\t\t\n");
      out.write("\t    \twindow.sessionStorage.setItem(\"isClick\",5);\n");
      out.write("\t\t\tif($(this).children('div.menuitem').length > 0 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    }; \n");
      out.write("\t    var click6=document.getElementById(\"click6\");\n");
      out.write("\t    click6.onclick = function(){\n");
      out.write("\t\t\t\n");
      out.write("\t    \twindow.sessionStorage.setItem(\"isClick\",6);\n");
      out.write("\t\t\tif($(this).children('div.menuitem').length > 0 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"men3title\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    }; \n");
      out.write("\t    \n");
      out.write("\t    var click7=document.getElementById(\"click7\");\n");
      out.write("\t    click7.onclick = function(){\n");
      out.write("\t\t\t\n");
      out.write("\t    \twindow.sessionStorage.setItem(\"isClick\",7);\n");
      out.write("\t\t\tif($(this).children('div.menuitem').length > 0 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t    }; \n");
      out.write("\t}else{\n");
      out.write("\t\t\n");
      out.write("\t\t $('.menupanel').on('click',function(){\n");
      out.write("\t\t\t\tif($(this).children().length > 1 ){\n");
      out.write("\t\t\t\t\t//$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t\t\tconsole.log($(this).children('div.menuitem')[0]);\n");
      out.write("\t\t\t\t\tvar clickid=window.sessionStorage.getItem(\"isClick\");\n");
      out.write("\t\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t//\t$(this).css(\"background-color\",\"#34485b\");\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#34485b\";\n");
      out.write("\t\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"menutitle\"+clickid).style.backgroundColor=\"#31a3ff\";\n");
      out.write("\t\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t}); \n");
      out.write("\t}\n");
      out.write("    \n");
      out.write("    /* $(document).ready(function(){\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"div.menupanel\").each(function(index){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(this).css(\"background-color\",\"#34485b\");\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"div.menuitem\").each(function(index){\n");
      out.write("\t\t\t$(this).css(\"display\",\"none\");\n");
      out.write("\t\t\tconsole.log($(this)[0].style.display);\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$('.menupanel').on('click',function(){\n");
      out.write("\t\t\tif($(this).children().length > 1 ){\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t\tconsole.log($(this).children('div.menuitem')[0]);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t\tif(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t\t\t$(this).css(\"background-color\",\"#34485b\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}); \n");
      out.write("\t\t\n");
      out.write("\t\t$('.menupanel').on('mouseover',function(){\n");
      out.write("\t\t\tif($(this).children().length > 1 ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"block\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$('.menupanel').on('mouseout',function(){\n");
      out.write("\t\t\tif($(this).children().length > 1 ){\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t\t$(this).css(\"background-color\",\"#34485b\");\n");
      out.write("\t\t\t\t$(this).children('div.menuitem').css(\"display\",\"none\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$('.menupanel').on('mouseover',function() {\n");
      out.write("\t\t\tif($(this).children().length > 1 ){\n");
      out.write("\t       \t\t $(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t}\n");
      out.write("\t   });\n");
      out.write("\t\t\n");
      out.write("\t\t$('.menupanel').on('mouseout',function() {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif($(this).children().length > 1 ){\n");
      out.write("\t\t\t    var dis = $(this).children('div.menuitem')[0].style.display;\n");
      out.write("\t\t\t    if(dis == \"\" || dis == \"block\"){\n");
      out.write("\t\t\t\t\t$(this).css(\"background-color\",\"#31a3ff\");\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t    $(this).css(\"background-color\",\"#34485b\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t   });\n");
      out.write("\t}) */\n");
      out.write("</script>");
      out.write("\n");
      out.write("\t\t\t \t</div>\n");
      out.write("\t\t\t\t<div class=\"floatleft content\" id=\"contentdivdiv\" name=\"contentdivdiv\">\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_sitemesh_005fbody_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"footer\">");
      out.write("\n");
      out.write("<!-- <div style=\"position: absolute; bottom: 0; height: 40px; width: 100%;background-color:#282828; \"></div> -->\n");
      out.write("</div>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t var contentdivdiv = window.document.getElementById('contentdivdiv');\n");
      out.write("\t var height=contentdivdiv.offsetHeight;\n");
      out.write("\t var menudivdiv = document.getElementById('menudivdiv');\n");
      out.write("\t menudivdiv.style.height = height+ 'px'; //这个就是直接给DIV的高度赋值。\n");
      out.write("\t/* var uaie = navigator.userAgent.toLowerCase().toString(); \n");
      out.write("\tif(/(msie\\s|trident.*rv:)([\\w.]+)/.test(uaie))\n");
      out.write("\t{\n");
      out.write("\t\tvar bodywidth=document.body.clientWidth; //BODY对象宽度 \n");
      out.write("\t\tvar bodyheight=document.body.clientHeight;//BODY对象高度 \n");
      out.write("\t\tvar xianwidth=document.documentElement.clientWidth;//可见区域宽度 \n");
      out.write("\t\tvar xianheight=document.documentElement.clientHeight;//可见区域高度 \n");
      out.write("\t\talert(bodyheight);\n");
      out.write("\t\talert(xianheight); \n");
      out.write("\t}else{\n");
      out.write("\t\t\n");
      out.write("\t\tvar bodywidth=document.documentElement.clientWidth; \n");
      out.write("\t\tvar bodyheight=document.documentElement.clientHeight;\n");
      out.write("\t\tvar divwidth=bodywidth*0.7925;\n");
      out.write("\t\tvar divheight=bodyheight;\n");
      out.write("\t\talert(divwidth);\n");
      out.write("\t\talert(divheight);\n");
      out.write("\t\tvar div1=document.getElementById(\"contentdivdiv\");\n");
      out.write("\t\tdiv1.style.width=divwidth+'px';\n");
      out.write("\t\tdiv1.style.height=divheight+'px';\n");
      out.write("\t} */\n");
      out.write("\t</script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/layouts/default.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/layouts/default.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/layouts/default.jsp(4,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_sitemesh_005fbody_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sitemesh:body
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jspx_th_sitemesh_005fbody_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.BodyTag) _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class);
    _jspx_th_sitemesh_005fbody_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sitemesh_005fbody_005f0.setParent(null);
    int _jspx_eval_sitemesh_005fbody_005f0 = _jspx_th_sitemesh_005fbody_005f0.doStartTag();
    if (_jspx_th_sitemesh_005fbody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody.reuse(_jspx_th_sitemesh_005fbody_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody.reuse(_jspx_th_sitemesh_005fbody_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/layouts/header.jsp(2,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("ctx");
    // /WEB-INF/layouts/header.jsp(2,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/layouts/header.jsp(2,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/layouts/header.jsp(12,175) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.usertype == 203}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('管');
        out.write('理');
        out.write('员');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/layouts/header.jsp(12,222) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.usertype == 202}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('客');
        out.write('户');
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /WEB-INF/layouts/menu.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("ctx");
    // /WEB-INF/layouts/menu.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/layouts/menu.jsp(3,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_sitemesh_005fbody_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sitemesh:body
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jspx_th_sitemesh_005fbody_005f1 = (com.opensymphony.module.sitemesh.taglib.decorator.BodyTag) _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class);
    _jspx_th_sitemesh_005fbody_005f1.setPageContext(_jspx_page_context);
    _jspx_th_sitemesh_005fbody_005f1.setParent(null);
    int _jspx_eval_sitemesh_005fbody_005f1 = _jspx_th_sitemesh_005fbody_005f1.doStartTag();
    if (_jspx_th_sitemesh_005fbody_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody.reuse(_jspx_th_sitemesh_005fbody_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fsitemesh_005fbody_005fnobody.reuse(_jspx_th_sitemesh_005fbody_005f1);
    return false;
  }
}
