/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2017-07-25 16:14:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/dev_tools/apache-tomcat-8.0.23/webapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500995551149L));
    _jspx_dependants.put("jar:file:/D:/dev_tools/apache-tomcat-8.0.23/webapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
	com.songfayuan.ssm.controller.CheckUserRight checkUserRight = new  com.songfayuan.ssm.controller.CheckUserRight(request);

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function editInfo(){\n");
      out.write("\t$(\"#editinfo\").hide();\n");
      out.write("\t$(\"#saveeditinfo\").show();\n");
      out.write("\t$(\"#probability\").removeAttr(\"disabled\");\n");
      out.write("\t$(\"#probability\").css(\"background-color\",\"rgb(255, 255, 255)\");\n");
      out.write("\t$(\"#probability\").focus();\n");
      out.write("}\n");
      out.write("function saveInfo(){\n");
      out.write("\t$(\"#editinfo\").show();\n");
      out.write("\t$(\"#saveeditinfo\").hide();\n");
      out.write("\t$(\"#probability\").attr(\"disabled\",\"disabled\");\n");
      out.write("\t$(\"#probability\").css(\"background-color\",\"#ff6600\");\n");
      out.write("\tvar probability = $(\"#probability\").val();\n");
      out.write("\t$.ajax(\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\turl:'");
      out.print(basePath);
      out.write("user/editinfo',\n");
      out.write("\t\t\t\ttype:'GET',\n");
      out.write("\t\t\t\tdata:'probability='+probability,\n");
      out.write("\t\t\t\tsuccess:function(data)\n");
      out.write("\t            {\n");
      out.write("\t\t\t\t\tif(data==\"yes\"){\n");
      out.write("\t\t\t\t\t\talert(\"平台收益率修改成功！\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif(data==\"no\"){\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t            }\n");
      out.write("\t        });\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div class=\"index_main\" style=\"width: 100%; height: 100%;\">\n");
      out.write("\n");
      out.write("<table class=\"list\" border=\"1\" bordercolor=\"#ccc\" cellspacing=\"10\" cellpadding=\"10\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td style=\"text-align: left;\">当前系统参数：</td>\n");
      out.write("\t\t<td style=\"text-align: left;\">【游鱼圈】运营播报：</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td style=\"text-align: left;\">\n");
      out.write("\t\t\t<div style=\"float: left;\"><img src=\"../images/computer.jpg\" style=\"width: 339px;\"/></div>\n");
      out.write("\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t<div class=\"index_line\">本机IP：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">本机名称:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer_hostName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">操作系统的名称：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer_os_Name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">操作系统的版本：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer_os_version }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">系统物理内存总计：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalphysicalmemorysize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">系统物理可用内存总计：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freephysicalmemorysize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">当前平台收益率：<input type=\"text\" id=\"probability\" name=\"probability\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${incomedata.probability }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled=\"disabled\" style=\"width: 80px; text-align: center; background-color: #ff6600; border-radius: 22px;\"/>\n");
      out.write("\t\t\t\t\t");
if(checkUserRight.check(100002)){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<span id=\"editinfo\" style=\"font-size: 15px; margin-left: 10px; color: #ff6600;cursor: pointer;\" onclick=\"editInfo();\">修改</span>\n");
      out.write("\t\t\t\t\t\t<span id=\"saveeditinfo\" style=\"font-size: 15px; margin-left: 10px; color: #ff6600;cursor: pointer;display:none;\" onclick=\"saveInfo();\"\">保存</span>\n");
      out.write("\t\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td style=\"text-align: left;\">\n");
      out.write("\t\t\t<div style=\"float: left;margin-top: 90px;\"><img src=\"../images/ditu.png\" style=\"width: 339px;padding-right: 8px;\"/></div>\n");
      out.write("\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t<div class=\"index_line\"></div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">截止到昨天23:59：</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\"><span style=\"color: #ff6600; font-size: 30px;\">平台收益：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${incomedata.money }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("元</span></div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">1、注册用户达<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(registuserlist)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</span>人，本月新增用户<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(monthAddList)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</span>人；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">2、广告查看数量达<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalcpm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>次；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">3、广告点击数量达<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalcpc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>次；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">4、您当前【进行中】订单数为：<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ordernum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">5、您当前【已结束】订单数为：<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${over_ordernum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">6、本日消费金额为：<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${todaymoney }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>元；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">7、本周消费金额为：<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weekmoney }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>元；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">8、本月消费金额为：<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${monthmoney }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>元；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">9、本年度消费金额为：<span style=\"color: #ff6600; font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${yearmoney }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>元；</div>\n");
      out.write("\t\t\t\t<div class=\"index_line\">我们共同的未来，源自你我的一份努力！</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\t\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- <table class=\"list\" border=\"1\" bordercolor=\"#ccc\" cellspacing=\"10\" cellpadding=\"10\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>\n");
      out.write("\t\t\t<div>©杭州数娱信息科技有限公司版权所有</div>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table> -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
