/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2017-07-25 16:13:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.apache.shiro.web.filter.authc.FormAuthenticationFilter;
import org.apache.shiro.authc.ExcessiveAttemptsException;
import org.apache.shiro.authc.IncorrectCredentialsException;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/dev_tools/apache-tomcat-8.0.23/webapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500995551149L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.shiro.web.filter.authc.FormAuthenticationFilter");
    _jspx_imports_classes.add("org.apache.shiro.authc.IncorrectCredentialsException");
    _jspx_imports_classes.add("org.apache.shiro.authc.ExcessiveAttemptsException");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction doChange(){\n");
      out.write("\t\tdocument.getElementById(\"code\").src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/validateCodeServlet?\"+Math.random();\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("\tbody\n");
      out.write("\t{\n");
      out.write("\t\tbackground: url('../images/loginbg.png');\n");
      out.write("\t\tbackground-repeat: no-repeat;\n");
      out.write("\t\tbackground-size:100% 100%;\n");
      out.write("/* \t\tbackground-size:auto 100%; */\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<form id=\"loginForm\" name=\"loginForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/login\" method=\"post\" class=\"form-horizontal\" onsubmit=\"return checkForm(loginForm)\">\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
	String error = (String) request.getAttribute(FormAuthenticationFilter.DEFAULT_ERROR_KEY_ATTRIBUTE_NAME);
	if(error != null){

      out.write("\n");
      out.write("\t<div class=\"alert alert-error input-medium controls\">\n");
      out.write("\t\t<button class=\"close\" data-dismiss=\"alert\">×</button>登录失败，请重试.\n");
      out.write("\t</div>\n");

    }

      out.write("\n");
      out.write("<div class=\"login-view\" style=\"\">\n");
      out.write("\t<div style=\"height: 70px; width: 100%;height: 100%\">\n");
      out.write("\t    <div style=\"height: 70px; font-size: 18px;font-weight: bold; line-height: 65px;\">\n");
      out.write("<!-- \t\t   <img src=\"../images/logo.png\" style=\"height:60px;margin-left:10px;margin-top:2px;float: left;\" /> -->\n");
      out.write("<!-- \t\t    <div style=\"font-size:36px;font-weight:bold;color:#333;width:60%;height: 70px;float: left;margin-left:20px;\">【游鱼圈】管理后台</div> -->\n");
      out.write("\t\t\t<div style=\"font-size: 36px; font-weight: bold; color: #fff; width: 100%; height: 70px; float: left; text-align: center; margin-top: 11.5%;\">『游鱼圈』推广系统管理后台</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"form\" style=\"\">\n");
      out.write("\t\t<div style=\"text-align: center; margin-top: 18px; font-size: 18px;font-weight: 600;\">\n");
      out.write("\t\t\t<img src=\"../images/logo.png\" style=\"height:100%;\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div style=\"background-color: #fff; height: 1.5px; width: 100%; margin-top: 2px;\"></div>\n");
      out.write("\t\t<div class=\"inner\">\n");
      out.write("\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t<div class=\"floatleft title\" style=\"\">用户名：</div>\n");
      out.write("\t\t\t\t<input class=\"\" type=\"text\" id=\"username\" name=\"username\"  maxlength=\"20\" />\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t<div class=\"floatleft title\" style=\"\">密 <label style=\"margin-left:9px;\">码</label>：</div>\n");
      out.write("\t\t\t\t<input class=\"\" type=\"password\" id=\"password\" name=\"password\"  maxlength=\"20\" />\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t<div class=\"floatleft title\" style=\"\">验证码：</div>\n");
      out.write("\t\t\t\t<input class=\"floatleft\" type=\"text\" id=\"validcode\" name=\"validcode\"  maxlength=\"4\" />\n");
      out.write("    \t\t\t<img class=\"floatleft validcodetext\" style=\"margin-top:2px;\" src=\"");
      out.print(basePath );
      out.write("validateCodeServlet\" id=\"code\" onclick=\"doChange();\" />\n");
      out.write("    \t\t\t<div class=\"floatleft validcoderefresh\"><a href=\"javascript:doChange();\">看不清</a></div>\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"item\">\n");
      out.write("\t\t\t\t<div class=\"floatleft title\" style=\"\">权 <label style=\"margin-left:9px;\">限</label>：</div>\n");
      out.write("\t\t\t\t<select name=\"usertype\" id=\"usertype\" style=\"width:276px;height:32px;border:1px solid #ddd;\">\n");
      out.write("\t\t\t\t  <option value=\"202\">客户</option>\n");
      out.write("\t\t\t\t  <option value=\"203\">管理员</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"item\" style=\"margin-left: -3px;\">\n");
      out.write("\t\t\t\t<input id=\"submit_btn\" class=\"greenbutton loginbutton\" style=\"width:100px;\" type=\"submit\" value=\"登录\"/>\n");
      out.write("\t\t\t\t<input id=\"submit_btn2\" class=\"greenbutton loginbutton\" style=\"width:100px;\" type=\"reset\" value=\"重置\"/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\"> \n");
      out.write("\n");
      out.write("function checkForm(form){\n");
      out.write("\tvar username = document.loginForm.username.value;\n");
      out.write("\tvar password = document.loginForm.password.value;\n");
      out.write("\tvar validcode = document.loginForm.validcode.value;\n");
      out.write("\tif(username.length==0){\n");
      out.write("\t\talert(\"用户名不能为空\");\n");
      out.write("\t\tdocument.loginForm.username.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(password.length==0){\n");
      out.write("\t\talert(\"密码不能为空\");\n");
      out.write("\t\tdocument.loginForm.password.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(validcode.length==0){\n");
      out.write("\t\talert(\"验证码不能为空\");\n");
      out.write("\t\tdocument.loginForm.validcode.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tdocument.loginForm.password.value = md5(password);\n");
      out.write("}\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/user/login.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/views/user/login.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/login.jsp(7,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
