/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2017-07-25 16:15:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/dev_tools/apache-tomcat-8.0.23/webapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500995551149L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
com.songfayuan.ssm.controller.CheckUserRight checkUserRight = new  com.songfayuan.ssm.controller.CheckUserRight(request);

      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("js/My97DatePicker/WdatePicker.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("<!--\n");
      out.write("table {\n");
      out.write("\twidth: 100%;\n");
      out.write("\ttext-align: left;\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("\tborder-spacing: 1;\n");
      out.write("\tborder-spacing: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table td {\n");
      out.write("\tword-break: break-all;\n");
      out.write("\tword-wrap: break-word;\n");
      out.write("\tborder-right: 1px solid #E7E5E5;\n");
      out.write("\tborder-bottom: 1px solid #E7E5E5;\n");
      out.write("/* \tfont: 500 14px Arial; */\n");
      out.write("\tcolor: #666666;\n");
      out.write("\tfont-size: 16px;\n");
      out.write("  /*   font-family: 微软雅黑; */\n");
      out.write("}\n");
      out.write("-->\n");
      out.write("</style>\n");
      out.write("<div class=\"navigation\">当前位置：接单人管理&nbsp;>&nbsp;接单人列表</div>\n");
      out.write("<form name=\"findForm\" id=\"findForm\" action=\"");
      out.print(basePath );
      out.write("user/userlist\" method=\"get\" style=\"margin-top: 20px; margin-left: 29px; color: #666666;\">\n");
      out.write("\t\t\t用 户 名:<input id=\"username\" type=\"text\" name=\"username\" style=\"width: 180px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"请输入用户名\">\n");
      out.write("<!-- \t\t<tr> -->\n");
      out.write("\t\t\t<!-- <td class=\"td_2\" colspan=\"2\" style=\"padding: 2px 2px 2px 12px;\">\n");
      out.write("\t\t\t\t注册时间:\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"starttime\" name=\"starttime\" maxlength=\"20\" style=\"width: 180px;\" onFocus=\"WdatePicker({isShowClear:true,readOnly:true,dateFmt:'yyyy-MM-dd HH:mm:ss'})\"   placeholder=\"请点击选择时间\"/>\n");
      out.write("\t\t\t\t至\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"endtime\" name=\"endtime\" maxlength=\"20\" style=\"width: 180px;\" onFocus=\"WdatePicker({isShowClear:true,readOnly:true,dateFmt:'yyyy-MM-dd HH:mm:ss'})\"    placeholder=\"请点击选择时间\"/>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</td> -->\n");
      out.write("<!-- \t\t</tr> -->\n");
      out.write("\t\t<input type=\"button\" class=\"greenbutton\" onclick=\"javasrcipt:submitForm()\" value=\"搜&nbsp;&nbsp;&nbsp;索\" style=\"margin-left: 80px;width: 85px; height: 36px;\">\n");
      out.write('\n');
      out.write("\n");
      out.write("</form><br/>\n");
      out.write("<form id=\"infoForm\" name=\"inputForm\" action=\"\" method=\"post\" class=\"form-horizontal\" >\n");
      out.write("<table class=\"list\" border=\"1\" bordercolor=\"#ccc\" cellspacing=\"10\" cellpadding=\"10\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<th><input type='checkbox' name=\"\" id=\"controlAll\"  onclick='if(this.checked==true) { selectAll(); } else { selectAll(); }' >全选</th>\n");
      out.write("\t\t<th>昵称</th>\n");
      out.write("\t\t<th>openid</th>\n");
      out.write("\t\t<th>手机号</th>\n");
      out.write("\t\t<th>注册时间</th>\n");
      out.write("\t\t<th>账户余额</th>\n");
      out.write("\t\t<th>累计收入</th>\n");
      out.write("\t\t<th>今日收入</th>\n");
      out.write("\t\t<th>操作</th>\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/user/userlist.jsp(64,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/userlist.jsp(64,1) '${userList.content}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${userList.content}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/user/userlist.jsp(64,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /WEB-INF/views/user/userlist.jsp(64,1) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t<tr> \n");
            out.write("\t\t\t<td><input type='checkbox' name='selected' value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onclick=\"choose()\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(userList.pageno-1)*10+status.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.createDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.balance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.totalmoney}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.todaymoney}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t<td>\n");
            out.write("\t\t\t\t<a style=\"color:#54bc2d;\" href=\"");
            out.print(basePath);
            out.write("user/userdetail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">详情</a>\n");
            out.write("\t\t\t\t<a style=\"color:#ff6600;\" href=\"");
            out.print(basePath);
            out.write("user/edit_marketing_condition?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">营销条件</a>\n");
            out.write("\t\t\t</td>\n");
            out.write("\t\t</tr>\t\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<br/>\n");
      out.write("<div style=\"margin-left: 29px;\">\n");
      out.write("\t<input type=\"hidden\" name=\"idlist\" id=\"idlist\"/>\n");
      out.write("\t<input id=\"daochu\" style=\"width: 80px;\" class=\"greenbutton\" type=\"button\" value=\"导出\" onclick=\"goToUrl()\"/>\n");
      out.write("\t<input id=\"shanchu\" style=\"width: 80px;\" class=\"greenbutton\" type=\"button\" value=\"删除\" onclick=\"goToUrl2()\"/>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"pagestart\">\n");
      out.write("\t<div class=\"pagebar\" style=\"margin-right: 10px; height: 20px; line-height: 20px;\">\n");
      out.write("\t\t共<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.totalpages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>页，每页<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pagesize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>条，当前是第<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>页\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"pageinfo\">\n");
      out.write("\t\t<button\n");
      out.write("\t\t\tonclick=\"gotopage('");
      out.print(basePath);
      out.write("user/userlist', '1')\"\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(">首页</button>\n");
      out.write("\t\t<button\n");
      out.write("\t\t\tonclick=\"gotopage('");
      out.print(basePath);
      out.write("user/userlist', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno-1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(">上页</button>\n");
      out.write("\t\t<button\n");
      out.write("\t\t\tonclick=\"gotopage('");
      out.print(basePath);
      out.write("user/userlist', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno+1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write(">下页</button>\n");
      out.write("\t\t<button\n");
      out.write("\t\t\tonclick=\"gotopage('");
      out.print(basePath);
      out.write("user/userlist', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.totalpages }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write(">末页</button>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"clear\"></div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("// alert('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\n");
      out.write("//提交查询表单\n");
      out.write("function submitForm(){\n");
      out.write("\t\n");
      out.write("/* \tif($(\"#startage\").val()==0){\n");
      out.write("\t\t$(\"#startage\").val(\"\");\n");
      out.write("\t}\n");
      out.write("\tif($(\"#endage\").val()==0){\n");
      out.write("\t\t$(\"#endage\").val(\"\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar startdate=0;\n");
      out.write("\tvar enddate=0;\n");
      out.write("\tif($(\"#starttime\").val()!=null&&$(\"#starttime\").val()!=\"\"&&$(\"#starttime\").val()!=undefined){\n");
      out.write("\t\tstartdate = new Date($(\"#starttime\").val());\n");
      out.write("\t\t$(\"#starttime1\").val(startdate.getTime());\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#starttime1\").val(0);\n");
      out.write("\t}\n");
      out.write("\tif($(\"#endtime\").val()!=null&&$(\"#endtime\").val()!=\"\"&&$(\"#endtime\").val()!=undefined){\n");
      out.write("\t\tenddate = new Date($(\"#endtime\").val());\n");
      out.write("\t\t$(\"#endtime1\").val(enddate.getTime());\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#endtime1\").val(0);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tif($(\"#startage\").val() == null || $(\"#startage\").val() == \"\" || $(\"#startage\").val() == undefined){\n");
      out.write("\t\t$(\"#startage\").val(0);\n");
      out.write("\t}\n");
      out.write("\tif($(\"#endage\").val() == null || $(\"#endage\").val() == \"\" || $(\"#endage\").val() == undefined){\n");
      out.write("\t\t$(\"#endage\").val(0);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tdocument.getElementById(\"pageno\").value=1; */\n");
      out.write("\t\n");
      out.write("\t/* var username = $(\"#username\").val();//用户名\n");
      out.write("\tvar sex = $(\"#sex\").val();//性别\n");
      out.write("\tvar medicalhistory = $(\"#medicalhistory\").val();//慢病\n");
      out.write("\tvar population = $(\"#population\").val();//群体\n");
      out.write("\tvar dietitianid = $(\"#dietitianid\").val();//营养师id\n");
      out.write("\tvar startage = $(\"#startage\").val();//开始年龄\n");
      out.write("\tvar endage = $(\"#endage\").val();//结束年龄\n");
      out.write("\tvar starttime1 = $(\"#starttime1\").val();//开始时间\n");
      out.write("\tvar endtime1 = $(\"#endtime1\").val();//结束时间 */\n");
      out.write("\t\n");
      out.write("\t/* alert(\"用户名=\"+username+\"--性别=\"+sex+\"--慢病=\"+medicalhistory+\"--群体=\"+population+\"--营养师id=\"+dietitianid+\"--开始年龄=\"+startage\n");
      out.write("\t\t\t+\"--结束年龄=\"+endage+\"--开始时间=\"+starttime1+\"--结束时间=\"+endtime1); */\n");
      out.write("\t\n");
      out.write("\t$('#findForm').submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function getValue(){\n");
      out.write("\tvar sexvalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sex}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#sex\").val(sexvalue);\n");
      out.write("\tvar medicalhistoryvalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${medicalhistory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#medicalhistory\").val(medicalhistoryvalue);\n");
      out.write("\tvar dietitianidvalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dietitianid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#dietitianid\").val(dietitianidvalue);\n");
      out.write("\tvar populationvalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${population}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#population\").val(populationvalue);\n");
      out.write("\tvar startagevalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#startage\").val(startagevalue);\n");
      out.write("\tvar endagevalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${endage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#endage\").val(endagevalue);\n");
      out.write("\t//alert(startagevalue+\"---\"+endagevalue);\n");
      out.write("\tvar starttimevalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${starttime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#starttime\").val(starttimevalue);\n");
      out.write("\tvar endtimevalue = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${endtime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t$(\"#endtime\").val(endtimevalue);\n");
      out.write("\t//alert(starttimevalue+\"---\"+endtimevalue);\n");
      out.write("}\n");
      out.write("\n");
      out.write("//分页\n");
      out.write("function gotopage1(basepath,pageno)\n");
      out.write("{\n");
      out.write("\tvar startdate=0;\n");
      out.write("\tvar enddate=0;\n");
      out.write("\tif($(\"#starttime\").val()!=null&&$(\"#starttime\").val()!=\"\"&&$(\"#starttime\").val()!=undefined){\n");
      out.write("\t\tstartdate = new Date($(\"#starttime\").val());\n");
      out.write("\t\t$(\"#starttime1\").val(startdate.getTime());\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#starttime1\").val(0);\n");
      out.write("\t}\n");
      out.write("\tif($(\"#endtime\").val()!=null&&$(\"#endtime\").val()!=\"\"&&$(\"#endtime\").val()!=undefined){\n");
      out.write("\t\tenddate = new Date($(\"#endtime\").val());\n");
      out.write("\t\t$(\"#endtime1\").val(enddate.getTime());\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#endtime1\").val(0);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar startage =  $(\"#startage\").val();\n");
      out.write("\tif(startage == null || startage == \"\" || startage == undefined){\n");
      out.write("\t\t$(\"#startage\").val(0);\n");
      out.write("\t}\n");
      out.write("\tvar endage =  $(\"#endage\").val();\n");
      out.write("\tif(endage == null || endage == \"\" || endage == undefined){\n");
      out.write("\t\t$(\"#endage\").val(0);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tdocument.getElementById(\"pageno\").value=pageno;\n");
      out.write("\t$('#findForm').submit();\n");
      out.write("\t/* window.location.href=basepath+\"?pageno=\"+pageno; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("//=====================全选/反选操作=======================\n");
      out.write("function selectAll(){\n");
      out.write("\t var checklist = document.getElementsByName (\"selected\");\n");
      out.write("\t if(document.getElementById(\"controlAll\").checked)\n");
      out.write("\t {\n");
      out.write("\t    for(var i=0;i<checklist.length;i++)\n");
      out.write("\t \t{\n");
      out.write("\t      checklist[i].checked = 1;\n");
      out.write("\t \t} \n");
      out.write("\t }else\n");
      out.write("\t {\n");
      out.write("\t     for(var j=0;j<checklist.length;j++)\n");
      out.write("\t\t {\n");
      out.write("\t\t     checklist[j].checked = 0;\n");
      out.write("\t\t }\n");
      out.write("\t }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function choose(){\n");
      out.write("\tvar selectType = $(\"input[name=selected]\");\n");
      out.write("\tvar selectTypeC = $(\"input[name='selected']:checked\");\n");
      out.write("\tif(selectType.length==selectTypeC.length){\n");
      out.write("\t\tdocument.getElementById(\"controlAll\").checked=true;\n");
      out.write("\t}else{\n");
      out.write("\t\tdocument.getElementById(\"controlAll\").checked=false;\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("//==================获取选中的值==================\n");
      out.write("function getInfo(){\n");
      out.write("\tdocument.getElementById(\"idlist\").value=\"\";\n");
      out.write("\tvar selectType = $(\"input[name=selected]\");\n");
      out.write("// \talert(selectType.length);\n");
      out.write("\tfor(var j=0;j<selectType.length;j++){\n");
      out.write("\t\tif( selectType[j].checked==true ){\n");
      out.write("\t\t\tvar chk_value = [];\n");
      out.write("\t\t\t//js获取复选框值    \n");
      out.write("\t\t\tvar obj = document.getElementsByName(\"selected\");//选择所有name=\"selected\"的对象，返回数组    \n");
      out.write("\t\t\tvar s='';//如果这样定义var s;变量s中会默认被赋个null值\n");
      out.write("\t\t\tfor(var i=0;i<obj.length;i++){\n");
      out.write("\t\t\t\t if(obj[i].checked) //取到对象数组后，我们来循环检测它是不是被选中\n");
      out.write("\t\t\t\t s+=obj[i].value+',';   //如果选中，将value添加到变量s中    \n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t//jquery获取复选框值    \n");
      out.write("\t\t\t$('input[name=\"selected\"]:checked').each(function(){//遍历每一个名字为selected的复选框，其中选中的执行函数    \n");
      out.write("\t\t\t\tchk_value.push($(this).val());//将选中的值添加到数组chk_value中    \n");
      out.write("\t\t\t});    \n");
      out.write("\t\t\tidlist = chk_value.toString();\n");
      out.write("\t \t\t//alert(idlist);\n");
      out.write("\t \t\tif(idlist != null && idlist != \"\" && idlist != undefined){\n");
      out.write("\t\t\t\tdocument.getElementById(\"idlist\").value=idlist;\n");
      out.write("\t \t\t}else{\n");
      out.write("\t \t\t\tdocument.getElementById(\"idlist\").value=\"\";\n");
      out.write("\t \t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("//==================判断是否做了选择==================\n");
      out.write("function checkForm(){\n");
      out.write("\tvar idlist=document.getElementById(\"idlist\").value;\n");
      out.write("\tif(idlist==''||idlist==null||idlist==undefined){\n");
      out.write("\t\talert(\"你还没有选择，请选择后再操作！\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\treturn true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("//======================删除数据===========================\n");
      out.write("function goToUrl2() {\n");
      out.write("\tgetInfo();\n");
      out.write("\tif (!checkForm()) {\n");
      out.write("\t\treturn;\n");
      out.write("\t}\n");
      out.write("\tvar result=checkForm(infoForm);\n");
      out.write("    if(result==false){\n");
      out.write("    \treturn;\n");
      out.write("    }else{\n");
      out.write("    \tvar panduan=confirm(\"确认删除吗?\");\n");
      out.write("    \tif (panduan==true){\n");
      out.write("// \t    \talert('请求成功！');\n");
      out.write("\t    \tvar idlist=document.getElementById(\"idlist\").value;\n");
      out.write("    \t\tinfoForm.action='");
      out.print(basePath);
      out.write("user/deleteUserById?idlist='+idlist;\n");
      out.write("\t    \tinfoForm.submit();\n");
      out.write("    \t}else{\n");
      out.write("    \t\t//alert('请求失败！');\n");
      out.write("    \t\tvar obj = document.getElementsByName(\"selected\");\n");
      out.write("\t\t\tfor(var i=0;i<obj.length;i++){\n");
      out.write("\t\t\t\tobj[i].checked=false;\n");
      out.write("\t\t\t}\n");
      out.write("    \t}\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("//=====================导出数据======================\n");
      out.write("function goToUrl() {\n");
      out.write("\tgetInfo();\n");
      out.write("\tvar idlist=document.getElementById(\"idlist\").value;\n");
      out.write("\t//alert(idlist);\n");
      out.write("   \tvar panduan=confirm(\"确认导出数据?\");\n");
      out.write("   \tif (panduan==true){\n");
      out.write("//     \talert('请求成功！');\n");
      out.write("   \t\tinfoForm.action='");
      out.print(basePath);
      out.write("user/exuserlist';\n");
      out.write("    \tinfoForm.submit();\n");
      out.write("   \t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/views/user/userlist.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/userlist.jsp(3,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(97,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button3\"  disabled");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(98,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno > 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button2\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(101,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button3\"  disabled");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(102,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno > 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button2\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(105,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno == userList.totalpages}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button3\"  disabled");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(106,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno < userList.totalpages}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button2\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f6.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(109,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno == userList.totalpages}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
    if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button3\"  disabled");
        int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f7.setParent(null);
    // /WEB-INF/views/user/userlist.jsp(110,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userList.pageno < userList.totalpages}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
    if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" class=\"button2\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
    return false;
  }
}
